#! /usr/bin/env bash

# Copyright © 2016 - 2018 Chris Egerton <fearthecellos@gmail.com>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See the LICENSE file for more details.

BASE_DIR=`dirname "$0"`
BASE_NAME=`basename $0`

JAR_FILE="$BASE_DIR/bin/arg.jar"
if ! [[ -f "$JAR_FILE" ]]; then
  echo -e "$0: could not locate jarfile at '$JAR_FILE'\n" \
      "You probably need to build the project; try running " \
      "'$BASE_DIR/gradlew distribute'"
  exit 1
fi

java -jar "$JAR_FILE" "$@"
